name: Ping RSI Streamlit App Daily

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 AM UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  wake-rsi-app:
    runs-on: ubuntu-latest

    steps:
      - name: Wait before pinging (optional delay)
        run: |
          echo "⏳ Waiting 60 seconds before pinging the RSI app..."
          sleep 60

      - name: Ping the RSI Streamlit app
        run: |
          echo "📡 Pinging RSI Streamlit app: https://rsialerts.streamlit.app/"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            https://rsialerts.streamlit.app/)

          echo "HTTP Status: $HTTP_STATUS"

          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ App is awake and responding."
          else
            echo "❌ Failed to reach app. HTTP status: $HTTP_STATUS"
            exit 1
          fi
